# Generated by Django 5.2.13 on 2026-04-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('accion', models.TextField()),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('ci_o_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('ci', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('cel', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nacionalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaVenta',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=300, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'nota_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'pedido_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disponible', models.BooleanField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id_salario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'salario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id_tipo_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'turno',
                'managed': False,
            },
        ),
    ]
